::

  sudo apt-get update
  sudo apt-get install -y debhelper build-essential autotools-dev golang
  git clone https://github.com/dotcloud/docker
  cd docker/packaging/debian
  make debian
  sudo dpkg -i lxc-docker_*-1_amd64.deb; sudo apt-get install -f -y