::

  git clone https://github.com/dotcloud/docker
  cd docker
  git checkout packaging
  make deb

Once launchpad is up, add to /etc/apt/sources.list::

  deb http://ppa.launchpad.net/noise+ppa/docker-dev/ubuntu precise main
